class AppSecrets{
  static const supabaseUrl= 'https://rwdvxuubdhgirnmcgfqu.supabase.co' ;
static const supabaseAnonKey='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3ZHZ4dXViZGhnaXJubWNnZnF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjQwNjU4NDUsImV4cCI6MjAzOTY0MTg0NX0.XxMc10JP5qFV1S7FzBwZ1muzuxuwz4vV_wzXoY7SaLU';
}